version: '3.9'
services:
  elgestionador:
    build: .
    container_name: elgestionador
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: unless-stopped
